"""Operator-run script to regenerate the public-surface snapshot files.

Plan 06-01 Task 3 — REFAC-01 safety net. Re-derives the 4 snapshot files
under ``verification/snapshots/`` by enumerating the current public
surface of each target package.

Operator usage (D-11)::

    uv run python verification/regen_snapshots.py

Run this AFTER an intentional change to any package's ``__all__`` (e.g.,
the per-package Client class skeleton lands in Plans 03-06 and adds
``Client``, ``AsyncClient``, ``close``, ``aclose``). Commit the snapshot
diff in the SAME commit as the source change that justifies it. Reviewers
should treat the snapshot diff as a code-review surface.

The header content in each snapshot file is purely documentation; the
companion test (:mod:`verification.test_public_surface`) strips
``#``-prefixed header lines from the expected file before comparing
against the enumerated surface, so editing header wording does not affect
the contract. The 8-line header invariant (W3) IS validated — the writer
below preserves it bit-for-bit.

The script imports the enumeration helpers lazily inside :func:`main` to
keep import-time side effects nil and avoid any pytest collection noise
when this file is scanned (PATTERNS.md Section 2 adaptation note).
"""

from __future__ import annotations

__all__ = ["main"]


# 8-line snapshot header. Lines 1-7 are documentation; line 8 is the
# header/body separator (exactly ``#`` alone). Kept literal here so that
# editors with auto-strip-trailing-whitespace cannot corrupt the
# separator silently.
_HEADER_TEMPLATE = (
    "# Public surface snapshot for {slug}.\n"
    "# Generated by: python verification/regen_snapshots.py\n"
    "# Format: <name> : <kind> : <signature>\n"
    "# Sort: stable alphabetical by name.\n"
    "# DO NOT EDIT BY HAND. To accept an intentional change, run the regen script\n"
    "# above and commit the diff alongside the source change that justifies it.\n"
    "# See PATTERNS.md Section 3 for the snapshot file convention.\n"
    "#\n"
)


def main() -> None:
    """Rewrite the 4 snapshot files and print one line per package."""
    # Lazy import: keeps this script's import-time surface zero and avoids
    # any pytest interaction when the file is touched at collection time.
    # Also ensure the repo root is on sys.path so `python
    # verification/regen_snapshots.py` works when invoked directly (the
    # script's parent directory is on sys.path by default, NOT the repo
    # root, so the `verification` package would otherwise be unresolvable
    # from this entry point).
    import sys
    from pathlib import Path

    repo_root = Path(__file__).resolve().parent.parent
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

    from verification.test_public_surface import (
        _PACKAGES,
        _enumerate_surface,
        _snapshot_path,
    )

    for pkg_name in _PACKAGES:
        slug = pkg_name.replace("_", "-")
        lines = _enumerate_surface(pkg_name)
        header = _HEADER_TEMPLATE.format(slug=slug)
        body = "\n".join(lines) + "\n"
        path = _snapshot_path(pkg_name)
        path.write_text(header + body)
        print(f"Wrote {path} ({len(lines)} symbols)")


if __name__ == "__main__":
    main()
